version: '3.7'

services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:v1.6.1
    volumes:
      - ./qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"
    restart: always
